# Hardware configuration — replace with your actual hardware-configuration.nix
# Generated by `nixos-generate-config` on your target machine.
#
# To use this configuration on real hardware:
#   1. Boot a NixOS installer
#   2. Run `nixos-generate-config --root /mnt`
#   3. Copy the generated /mnt/etc/nixos/hardware-configuration.nix here
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Kernel modules — adjust to your hardware
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ]; # Change to kvm-amd for AMD CPUs
  boot.extraModulePackages = [ ];

  # File systems — replace with your actual partitions
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
